baseurl = "https://amalsoman.com/"
languageCode = "en-US"
title = "Amal Soman"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""
theme = "hugo-sustain-vitae"

[permalinks]
  post = "/:year/:month/:day/:slug"

[params]
  avatar = "profile.png"
  author = "Amal Soman"
  description = "Describe your website"

  # Custom assets can be linked with their paths relative to static/
  custom_css = []
  custom_js  = []

[params.social]
  Github        = "amalsom10"
  Email         = "amalsoman10@gmail.com"
  Twitter       = "amalsom10"
  LinkedIn      = "amalsoman"
  Stackoverflow = "username"
  Medium        = "username"

[params.vitae]
  website = "amalsoman.com"
  website_full = "https://amalsoman.com"
  city = "Bangalore"
  country = "India"

## Main Menu
[[menu.main]]
  name = "blog"
  weight = 100
  identifier = "blog"
  url = "https://exploriaa.com/amal-soman/"
[[menu.main]]
  name = "projects"
  identifier = "projects"
  weight = 200
  url = "/projects/"
[[menu.main]]
  name = "resume"
  identifier = "resume"
  weight = 300
  url = "/vitae/"
